const vocabularies = {
  ru: {
    numberWords: {
      0: 'ноль ',
      1: 'один ',
      2: 'два ',
      3: 'три ',
      4: 'четыре ',
      5: 'пять ',
      6: 'шесть ',
      7: 'семь ',
      8: 'восемь ',
      9: 'девять ',
      10: 'десять ',
      11: 'одиннадцать ',
      12: 'двенадцать ',
      13: 'тринадцать ',
      14: 'четырнадцать ',
      15: 'пятнадцать ',
      16: 'шестнадцать ',
      17: 'семнадцать ',
      18: 'восемнадцать ',
      19: 'девятнадцать ',
      20: 'двадцать ',
      30: 'тридцать ',
      40: 'сорок ',
      50: 'петьдесять ',
      60: 'шестьдесять ',
      70: 'семьдесять ',
      80: 'восемьдесять ',
      90: 'девяносто ',
    },
    numberZeros: {
      1: 'десять ',
      2: 'сто ',
      3: 'тысяча ',
      6: 'миллион ',
    },
    operations: {
      '-': 'минус ',
      '+': 'плюс ',
      '*': 'умножить ',
      '/': 'делить ',
      '.': 'точка ',
    },
  },
  en: {
    numberWords: {
      0: 'zero ',
      1: 'one ',
      2: 'two ',
      3: 'three ',
      4: 'four ',
      5: 'five ',
      6: 'six ',
      7: 'seven ',
      8: 'eight ',
      9: 'nine ',
      10: 'ten ',
      11: 'eleven ',
      12: 'twelve ',
      13: 'thirteen ',
      14: 'fourteen ',
      15: 'fifteen ',
      16: 'sixteen ',
      17: 'seventeen ',
      18: 'eighteen ',
      19: 'nineteen ',
      20: 'twenty ',
      30: 'thirty ',
      40: 'forty ',
      50: 'fifty ',
      60: 'sixty ',
      70: 'seventy ',
      80: 'eighty ',
      90: 'ninety ',
    },
    numberZeros: {
      1: 'ten ',
      2: 'hundred ',
      3: 'thousand ',
      6: 'million ',
    },
    operations: {
      '-': 'minus ',
      '+': 'plus ',
      '*': 'times ',
      '/': 'over ',
      '.': 'point ',
    },
  },
}

module.exports = { ru: vocabularies.ru, en: vocabularies.en }
